In [21]:
import pandas as pd

In [17]:
df_TS = pd.read_csv("../data/7_annotations_repos/TS_repo_annotations.csv")
df_RG = pd.read_csv("../data/7_annotations_repos/RG_repo_annotations.csv")

In [18]:
df_to_annotate = pd.read_csv("../data/7_annotations_repos/df_to_annotate.csv")

In [27]:
df_annotated = pd.read_csv("df_repo_annotation_side_by_side.csv")

In [29]:
# remove rows where PMCID is NaN
_before = len(df_annotated)
df_annotated.dropna(subset=["PMCID"], inplace=True)
_after = len(df_annotated)
print(f"Removed {_before - _after} rows with NaN PMCID (remaining: {_after})")

Removed 17 rows with NaN PMCID (remaining: 35)

In [30]:
df_annotated

,PMCID,repo_url,repo_empty_TS,repo_empty_RG,repo_empty,readme_included_TS,readme_included_RG,readme_included,readme_overview_TS,readme_overview_RG,...,hardware_requirements,link_to_paper_TS,link_to_paper_RG,link_to_paper,citation_file_TS,citation_file_RG,citation_file,sample_dataset_TS,sample_dataset_RG,sample_dataset
0,PMC11307559,https://seakheeoh76.shinyapps.io/XGBoost_BA_prediction,NaN,Yes,Yes,NaN,No,No,NaN,No,...,No,NaN,No,No,NaN,No,No,NaN,NaN,No
1,PMC12121029,https://github.com/EnzhaoZhu/Common-risks-prediction-among-psychiatric-inpatients,No,No,No,Yes,Yes,Yes,No,Yes,...,No,No,No,No,No,No,No,No,No,No
2,PMC11701130,https://github.com/CalvinSMU/AiLES,Yes,No,Yes,Yes,Yes,Yes,No,No,...,No,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No
3,PMC8175333,https://github.com/ATARIQ5,NaN,NaN,Yes,NaN,NaN,No,NaN,NaN,...,No,NaN,NaN,No,NaN,NaN,No,NaN,NaN,No
4,PMC8932490,https://github.com/Aneja-Lab-Yale/Aneja-Lab-Public-Adversarial-Imaging,No,No,No,Yes,Yes,Yes,Yes,Yes,...,No,Yes,Yes,Yes,No,No,No,No,No,No
5,PMC11040883,https://github.com/laamit/champCalculator,No,No,No,Yes,Yes,Yes,Yes,Yes,...,No,No,No,No,No,No,No,Yes,Yes,Yes
6,PMC10545794,https://github.com/TheDecodeLab/Prediction_of_CDI_by_EHR_and_Genetics,No,No,No,Yes,Yes,Yes,No,No,...,No,No,No,No,No,No,No,No,No,No
7,PMC10658003,https://github.com/IreneSophia/MLSPE,No,No,No,Yes,Yes,Yes,Yes,Yes,...,No,No,No,No,Yes,Yes,Yes,No,No,No
8,PMC9720950,https://github.com/mi-erasmusmc/EmcDementiaModelValidation,No,No,No,Yes,Yes,Yes,Yes,Yes,...,No,No,No,No,No,No,No,No,No,No
9,PMC9653436,https://github.com/Dexin-Chen/Pathomics-analysis,No,No,No,No,No,No,No,No,...,No,No,No,No,No,No,No,No,No,No
10,PMC8881932,https://doi.org/10.5281/zenodo.4560078,No,No,No,Yes,Yes,Yes,No,Yes,...,No,No,No,No,No,No,No,Yes,Yes,Yes
11,PMC9898833,https://github.com/jacksoncoki/Emergency-data-processing,No,No,No,Yes,Yes,Yes,No,No,...,Yes,No,No,No,No,No,No,No,No,No
12,PMC6413892,https://github.com/dt433/Predict-Prostate,No,No,No,No,No,No,No,No,...,No,No,No,No,No,No,No,No,No,No
13,PMC9685866,https://doi.org/10.57770/QTYQZS,No,NaN,No,Yes,NaN,Yes,No,NaN,...,No,No,NaN,No,No,NaN,No,Yes,NaN,No
14,PMC6461273,https://osf.io/w7aes/,No,No,No,No,No,No,No,No,...,No,No,No,No,No,No,No,No,No,No
15,PMC11624760,https://github.com/sersanmarsergio/SGA_prediction,No,No,No,Yes,Yes,Yes,Yes,Yes,...,No,No,No,No,No,No,No,No,No,No
16,PMC9978473,https://github.com/putzfn/HNLNL_autosegmentation_trained_models,No,No,No,Yes,Yes,Yes,No,No,...,No,No,No,No,No,No,No,No,No,No
17,PMC8593277,https://github.com/KosorokLab/CovidIBDRiskCalc,No,No,No,Yes,Yes,Yes,Yes,Yes,...,No,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No
18,PMC9872743,https://github.com/JohnLeo-XJTU/PerLesionDet_for_Oph-The,No,No,No,Yes,Yes,Yes,Yes,No,...,No,No,No,No,Yes,Yes,Yes,Yes,No,No
19,PMC11992218,https://www.cdc.gov/nchs/nhanes/index.htm,NaN,Yes,Yes,NaN,No,No,NaN,No,...,No,NaN,No,No,NaN,No,No,NaN,No,No
20,PMC10844206,https://github.com/benli12345/LEO-ML-NSQIP,No,No,No,Yes,Yes,Yes,No,Yes,...,No,No,No,No,No,No,No,No,No,No
21,PMC10844815,https://github.com/yiwangz/SS_learning/MLinHCT,NaN,Yes,Yes,NaN,No,No,NaN,No,...,No,NaN,No,No,NaN,No,No,NaN,No,No
22,PMC7797735,https://github.com/carsaesi/covid19sdtool,No,No,No,Yes,Yes,Yes,Yes,Yes,...,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes
23,PMC10937994,https://github.com/bounassif/Adenoma-Detector,No,No,No,No,No,No,No,No,...,No,No,No,No,No,No,No,No,No,No
24,PMC10491759,https://github.com/ShinyShine-820/LPAprediction,No,No,No,No,No,No,No,No,...,No,No,No,No,No,No,No,No,No,No
25,PMC10077108,https://github.com/mgregorich/BEAt-DKD_PredeGFR,No,No,No,Yes,Yes,Yes,Yes,Yes,...,No,No,No,No,Yes,Yes,Yes,No,No,No
26,PMC9913376,https://github.com/LFairleySmith/MyelomaPrediction,No,No,No,Yes,Yes,Yes,Yes,No,...,No,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No
27,PMC11257923,https://github.com/tsryo/evalFL,No,No,No,Yes,Yes,Yes,No,No,...,No,No,No,No,No,No,No,No,No,No
28,PMC11938237,https://github.com/SCYAN0401/Predict-GC-LNM,No,No,No,Yes,Yes,Yes,No,No,...,No,No,No,No,No,No,No,Yes,Yes,Yes
29,PMC11722487,https://github.com/weissman-lab/restriction,No,No,No,Yes,Yes,Yes,No,Yes,...,No,No,No,No,No,Yes,Yes,No,No,No
30,PMC8784888,https://github.com/AkihiroShiroshita/Prediction-model-for-Pnuemonic-COPD-exacerbation.git,NaN,Yes,Yes,NaN,No,No,NaN,No,...,No,NaN,No,No,NaN,No,No,NaN,No,No
31,PMC10955037,https://github.com/Exeter-Diabetes/CPRD-Pedro-SGLT2vsGLP1,No,No,No,Yes,Yes,Yes,Yes,Yes,...,No,No,No,No,No,No,No,No,No,No
32,PMC10100433,https://github.com/damiankotevski/head-and-neck-cancer-specific-survival,No,No,No,Yes,Yes,Yes,Yes,No,...,No,No,No,No,No,No,No,No,No,No
33,PMC8290951,https://github.com/mottenhoff/covid19_CDSS,No,No,No,Yes,Yes,Yes,Yes,No,...,No,No,No,No,No,No,No,No,No,No
34,PMC11827575,https://github.com/MGensheimer/prognosis-model,No,No,No,Yes,Yes,Yes,No,No,...,No,No,Yes,Yes,No,No,No,Yes,Yes,Yes

In [31]:
# Drop columns in df_annotated that end with _TS or _RG
cols_to_drop = [c for c in df_annotated.columns if c.endswith("_TS") or c.endswith("_RG")]
if cols_to_drop:
    df_annotated.drop(columns=cols_to_drop, inplace=True)

print(f"Dropped {len(cols_to_drop)} columns.")

Dropped 28 columns.

In [32]:
df_annotated

,PMCID,repo_url,repo_empty,readme_included,readme_overview,requirements_included,dependency_versions,license_included,inline_documentation,modularity,unit_testing,seed_reproducibility,hardware_requirements,link_to_paper,citation_file,sample_dataset
0,PMC11307559,https://seakheeoh76.shinyapps.io/XGBoost_BA_prediction,Yes,No,No,No,No,No,No,No,No,No,No,No,No,No
1,PMC12121029,https://github.com/EnzhaoZhu/Common-risks-prediction-among-psychiatric-inpatients,No,Yes,Yes,Yes,Yes,No,No,Yes,No,No,No,No,No,No
2,PMC11701130,https://github.com/CalvinSMU/AiLES,Yes,Yes,No,No,No,No,No,No,No,No,No,Yes,Yes,No
3,PMC8175333,https://github.com/ATARIQ5,Yes,No,No,No,No,No,No,No,No,No,No,No,No,No
4,PMC8932490,https://github.com/Aneja-Lab-Yale/Aneja-Lab-Public-Adversarial-Imaging,No,Yes,Yes,Yes,Yes,No,Yes,Yes,No,No,No,Yes,No,No
5,PMC11040883,https://github.com/laamit/champCalculator,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,No,Yes
6,PMC10545794,https://github.com/TheDecodeLab/Prediction_of_CDI_by_EHR_and_Genetics,No,Yes,No,No,No,Yes,No,No,No,Yes,No,No,No,No
7,PMC10658003,https://github.com/IreneSophia/MLSPE,No,Yes,Yes,No,No,No,Yes,Yes,No,No,No,No,Yes,No
8,PMC9720950,https://github.com/mi-erasmusmc/EmcDementiaModelValidation,No,Yes,Yes,No,No,No,No,Yes,No,No,No,No,No,No
9,PMC9653436,https://github.com/Dexin-Chen/Pathomics-analysis,No,No,No,No,No,No,No,No,No,Yes,No,No,No,No
10,PMC8881932,https://doi.org/10.5281/zenodo.4560078,No,Yes,No,Yes,Yes,Yes,No,Yes,No,Yes,No,No,No,Yes
11,PMC9898833,https://github.com/jacksoncoki/Emergency-data-processing,No,Yes,No,No,No,No,No,Yes,No,No,Yes,No,No,No
12,PMC6413892,https://github.com/dt433/Predict-Prostate,No,No,No,No,No,No,Yes,No,No,No,No,No,No,No
13,PMC9685866,https://doi.org/10.57770/QTYQZS,No,Yes,No,No,No,No,No,Yes,No,No,No,No,No,No
14,PMC6461273,https://osf.io/w7aes/,No,No,No,No,No,No,Yes,No,No,Yes,No,No,No,No
15,PMC11624760,https://github.com/sersanmarsergio/SGA_prediction,No,Yes,Yes,No,No,No,Yes,No,No,Yes,No,No,No,No
16,PMC9978473,https://github.com/putzfn/HNLNL_autosegmentation_trained_models,No,Yes,No,No,No,Yes,No,Yes,No,No,No,No,No,No
17,PMC8593277,https://github.com/KosorokLab/CovidIBDRiskCalc,No,Yes,Yes,No,No,No,Yes,Yes,No,No,No,Yes,Yes,No
18,PMC9872743,https://github.com/JohnLeo-XJTU/PerLesionDet_for_Oph-The,No,Yes,No,No,No,No,No,Yes,No,Yes,No,No,Yes,No
19,PMC11992218,https://www.cdc.gov/nchs/nhanes/index.htm,Yes,No,No,No,No,No,No,No,No,No,No,No,No,No
20,PMC10844206,https://github.com/benli12345/LEO-ML-NSQIP,No,Yes,No,No,No,No,Yes,No,No,Yes,No,No,No,No
21,PMC10844815,https://github.com/yiwangz/SS_learning/MLinHCT,Yes,No,No,No,No,No,No,No,No,No,No,No,No,No
22,PMC7797735,https://github.com/carsaesi/covid19sdtool,No,Yes,Yes,No,No,Yes,Yes,Yes,No,No,No,Yes,Yes,Yes
23,PMC10937994,https://github.com/bounassif/Adenoma-Detector,No,No,No,No,No,Yes,No,Yes,No,No,No,No,No,No
24,PMC10491759,https://github.com/ShinyShine-820/LPAprediction,No,No,No,Yes,Yes,No,No,No,No,No,No,No,No,No
25,PMC10077108,https://github.com/mgregorich/BEAt-DKD_PredeGFR,No,Yes,Yes,No,No,No,Yes,Yes,No,Yes,No,No,Yes,No
26,PMC9913376,https://github.com/LFairleySmith/MyelomaPrediction,No,Yes,Yes,No,No,No,Yes,Yes,No,No,No,Yes,Yes,No
27,PMC11257923,https://github.com/tsryo/evalFL,No,Yes,No,No,No,Yes,No,Yes,No,No,No,No,No,No
28,PMC11938237,https://github.com/SCYAN0401/Predict-GC-LNM,No,Yes,No,No,No,No,No,Yes,No,Yes,No,No,No,Yes
29,PMC11722487,https://github.com/weissman-lab/restriction,No,Yes,No,No,No,No,No,No,No,No,No,No,Yes,No
30,PMC8784888,https://github.com/AkihiroShiroshita/Prediction-model-for-Pnuemonic-COPD-exacerbation.git,Yes,No,No,No,No,No,No,No,No,No,No,No,No,No
31,PMC10955037,https://github.com/Exeter-Diabetes/CPRD-Pedro-SGLT2vsGLP1,No,Yes,Yes,No,No,Yes,Yes,Yes,No,Yes,No,No,No,No
32,PMC10100433,https://github.com/damiankotevski/head-and-neck-cancer-specific-survival,No,Yes,Yes,No,No,No,No,No,No,Yes,No,No,No,No
33,PMC8290951,https://github.com/mottenhoff/covid19_CDSS,No,Yes,Yes,Yes,Yes,No,No,Yes,No,No,No,No,No,No
34,PMC11827575,https://github.com/MGensheimer/prognosis-model,No,Yes,No,No,No,No,No,Yes,No,No,No,Yes,No,Yes

In [34]:
df_annotated.to_csv("repo_annotations.csv", index=False)

In [20]:
# List of annotation fields
question_cols = [
    "repo_empty",
    "readme_included",
    "readme_overview",
    "requirements_included",
    "dependency_versions",
    "license_included",
    # "coding_conventions",
    # "linter_formatter",
    "inline_documentation",
    "modularity",
    "unit_testing",
    # "ci_framework",
    "seed_reproducibility",
    "hardware_requirements",
    # "reporting_guidance",
    "link_to_paper",
    "citation_file",
    # "api_version_documented",
    "sample_dataset",
    # "dataset_link",
    # "confidential_data_excluded",
    # "env_variables_used",
]

# Start from df_to_annotate
df_out = df_to_annotate.copy()

# --- Merge in TS annotations ---
df_TS_sub = df_TS[["PMCID", "repo_url"] + question_cols].copy()
df_out = df_out.merge(
    df_TS_sub.add_suffix("_TS").rename(columns={"PMCID_TS": "PMCID", "repo_url_TS": "repo_url"}),
    on=["PMCID", "repo_url"],
    how="left"
)

# --- Merge in RG annotations ---
df_RG_sub = df_RG[["PMCID", "repo_url"] + question_cols].copy()
df_out = df_out.merge(
    df_RG_sub.add_suffix("_RG").rename(columns={"PMCID_RG": "PMCID", "repo_url_RG": "repo_url"}),
    on=["PMCID", "repo_url"],
    how="left"
)

# Original columns first
base_cols = ["PMCID", "repo_url"]

# Then interleave TS/RG for each question
paired_cols = []
for q in question_cols:
    paired_cols.append(f"{q}_TS")
    paired_cols.append(f"{q}_RG")

# Final column order
final_cols = base_cols + paired_cols

df_out = df_out[final_cols]

# Save to CSV
output_path = "df_repo_annotation_side_by_side.csv"
df_out.to_csv(output_path, index=False)

print(f"Saved merged CSV to: {output_path}")

Saved merged CSV to: df_repo_annotation_side_by_side.csv

In [5]:
import pandas as pd
from sklearn.metrics import cohen_kappa_score

# --- Load data ---
df_to_annotate = df_to_annotate  # already in memory
df_TS = pd.read_csv("../data/7_annotations_repos/TS_repo_annotations.csv")
df_RG = pd.read_csv("../data/7_annotations_repos/RG_repo_annotations.csv")

# --- Columns that correspond to actual annotation questions ---
question_cols = [
    "repo_empty",
    "readme_included",
    "readme_overview",
    "requirements_included",
    "dependency_versions",
    "license_included",
    "coding_conventions",
    "linter_formatter",
    "inline_documentation",
    "modularity",
    "unit_testing",
    "ci_framework",
    "seed_reproducibility",
    "hardware_requirements",
    "reporting_guidance",
    "link_to_paper",
    "citation_file",
    "api_version_documented",
    "sample_dataset",
    "dataset_link",
    "confidential_data_excluded",
    "env_variables_used",
]

# --- Restrict each annotator to repos we care about (optional but usually desired) ---
pmcid_set = set(df_to_annotate["PMCID"])
df_TS_sub = df_TS[df_TS["PMCID"].isin(pmcid_set)].copy()
df_RG_sub = df_RG[df_RG["PMCID"].isin(pmcid_set)].copy()

# --- Inner join on PMCID + repo_url to get only repos both annotated ---
df_both = df_TS_sub.merge(
    df_RG_sub,
    on=["PMCID", "repo_url"],
    suffixes=("_TS", "_RG"),
    how="inner",
)

print(f"Total repos to annotate: {len(df_to_annotate)}")
print(f"TS annotated: {df_TS_sub['PMCID'].nunique()} unique PMCIDs")
print(f"RG annotated: {df_RG_sub['PMCID'].nunique()} unique PMCIDs")
print(f"Overlap (both annotated): {df_both['PMCID'].nunique()} unique PMCIDs\n")

# --- Build long-form side-by-side table for all questions (optional but handy) ---
rows = []
for q in question_cols:
    ts_col = f"{q}_TS"
    rg_col = f"{q}_RG"
    if ts_col not in df_both.columns or rg_col not in df_both.columns:
        continue

    for _, row in df_both[["PMCID", "repo_url", ts_col, rg_col]].iterrows():
        rows.append(
            {
                "PMCID": row["PMCID"],
                "repo_url": row["repo_url"],
                "question": q,
                "TS_label": row[ts_col],
                "RG_label": row[rg_col],
            }
        )

df_side_by_side = pd.DataFrame(rows)

# print("Example of side-by-side annotations (first 10 rows):")
# print(df_side_by_side.head(10), "\n")

# --- Per-question stats + agreement ---
summary_rows = []

for q in question_cols:
    ts_col = f"{q}_TS"
    rg_col = f"{q}_RG"
    if ts_col not in df_both.columns or rg_col not in df_both.columns:
        continue

    # Non-null counts per annotator
    n_TS = df_both[ts_col].notna().sum()
    n_RG = df_both[rg_col].notna().sum()

    # Only rows where both annotators provided a label
    sub = df_both[[ts_col, rg_col]].dropna()
    n_both = len(sub)

    if n_both > 0:
        # Raw agreement
        agreement = (sub[ts_col] == sub[rg_col]).mean()

        # Cohen's kappa (handle degenerate cases)
        try:
            kappa = cohen_kappa_score(sub[ts_col], sub[rg_col])
        except Exception:
            kappa = float("nan")
    else:
        agreement = float("nan")
        kappa = float("nan")

    # Label distributions
    ts_counts = df_both[ts_col].value_counts(dropna=False)
    rg_counts = df_both[rg_col].value_counts(dropna=False)

    print(f"=== Question: {q} ===")
    print("TS label counts:")
    print(ts_counts)
    print("\nRG label counts:")
    print(rg_counts)
    print(f"\nN_TS (non-null): {n_TS}")
    print(f"N_RG (non-null): {n_RG}")
    print(f"N_both (for agreement): {n_both}")
    print(f"Percent agreement: {agreement:.3f}" if n_both > 0 else "Percent agreement: N/A")
    print(f"Cohen's kappa: {kappa:.3f}" if n_both > 0 else "Cohen's kappa: N/A")
    print("-" * 60)

    summary_rows.append(
        {
            "question": q,
            "N_TS": n_TS,
            "N_RG": n_RG,
            "N_both": n_both,
            "agreement": agreement,
            "kappa": kappa,
        }
    )

summary_df = pd.DataFrame(summary_rows).sort_values("question")
print("\n=== Summary table (per-question agreement) ===")
print(summary_df)

Total repos to annotate: 35
TS annotated: 30 unique PMCIDs
RG annotated: 33 unique PMCIDs
Overlap (both annotated): 29 unique PMCIDs

=== Question: repo_empty ===
TS label counts:
repo_empty_TS
No     28
Yes     1
Name: count, dtype: int64

RG label counts:
repo_empty_RG
No    29
Name: count, dtype: int64

N_TS (non-null): 29
N_RG (non-null): 29
N_both (for agreement): 29
Percent agreement: 0.966
Cohen's kappa: 0.000
------------------------------------------------------------
=== Question: readme_included ===
TS label counts:
readme_included_TS
Yes    24
No      5
Name: count, dtype: int64

RG label counts:
readme_included_RG
Yes    24
No      5
Name: count, dtype: int64

N_TS (non-null): 29
N_RG (non-null): 29
N_both (for agreement): 29
Percent agreement: 1.000
Cohen's kappa: 1.000
------------------------------------------------------------
=== Question: readme_overview ===
TS label counts:
readme_overview_TS
No     16
Yes    13
Name: count, dtype: int64

RG label counts:
readme_overview_RG
No     16
Yes    13
Name: count, dtype: int64

N_TS (non-null): 29
N_RG (non-null): 29
N_both (for agreement): 29
Percent agreement: 0.724
Cohen's kappa: 0.442
------------------------------------------------------------
=== Question: requirements_included ===
TS label counts:
requirements_included_TS
No     20
Yes     9
Name: count, dtype: int64

RG label counts:
requirements_included_RG
No     24
Yes     5
Name: count, dtype: int64

N_TS (non-null): 29
N_RG (non-null): 29
N_both (for agreement): 29
Percent agreement: 0.862
Cohen's kappa: 0.633
------------------------------------------------------------
=== Question: dependency_versions ===
TS label counts:
dependency_versions_TS
No     23
Yes     6
Name: count, dtype: int64

RG label counts:
dependency_versions_RG
No     24
Yes     5
Name: count, dtype: int64

N_TS (non-null): 29
N_RG (non-null): 29
N_both (for agreement): 29
Percent agreement: 0.966
Cohen's kappa: 0.888
------------------------------------------------------------
=== Question: license_included ===
TS label counts:
license_included_TS
No     21
Yes     8
Name: count, dtype: int64

RG label counts:
license_included_RG
No     21
Yes     8
Name: count, dtype: int64

N_TS (non-null): 29
N_RG (non-null): 29
N_both (for agreement): 29
Percent agreement: 1.000
Cohen's kappa: 1.000
------------------------------------------------------------
=== Question: coding_conventions ===
TS label counts:
coding_conventions_TS
Yes    21
No      8
Name: count, dtype: int64

RG label counts:
coding_conventions_RG
No     20
Yes     9
Name: count, dtype: int64

N_TS (non-null): 29
N_RG (non-null): 29
N_both (for agreement): 29
Percent agreement: 0.586
Cohen's kappa: 0.293
------------------------------------------------------------
=== Question: linter_formatter ===
TS label counts:
linter_formatter_TS
No    29
Name: count, dtype: int64

RG label counts:
linter_formatter_RG
No    29
Name: count, dtype: int64

N_TS (non-null): 29
N_RG (non-null): 29
N_both (for agreement): 29
Percent agreement: 1.000
Cohen's kappa: nan
------------------------------------------------------------
=== Question: inline_documentation ===
TS label counts:
inline_documentation_TS
Yes    15
No     14
Name: count, dtype: int64

RG label counts:
inline_documentation_RG
No     17
Yes    12
Name: count, dtype: int64

N_TS (non-null): 29
N_RG (non-null): 29
N_both (for agreement): 29
Percent agreement: 0.690
Cohen's kappa: 0.383
------------------------------------------------------------
=== Question: modularity ===
TS label counts:
modularity_TS
Yes    20
No      9
Name: count, dtype: int64

RG label counts:
modularity_RG
Yes    18
No     11
Name: count, dtype: int64

N_TS (non-null): 29
N_RG (non-null): 29
N_both (for agreement): 29
Percent agreement: 0.931
Cohen's kappa: 0.848
------------------------------------------------------------
=== Question: unit_testing ===
TS label counts:
unit_testing_TS
No     28
Yes     1
Name: count, dtype: int64

RG label counts:
unit_testing_RG
No    29
Name: count, dtype: int64

N_TS (non-null): 29
N_RG (non-null): 29
N_both (for agreement): 29
Percent agreement: 0.966
Cohen's kappa: 0.000
------------------------------------------------------------
=== Question: ci_framework ===
TS label counts:
ci_framework_TS
No    29
Name: count, dtype: int64

RG label counts:
ci_framework_RG
No    29
Name: count, dtype: int64

N_TS (non-null): 29
N_RG (non-null): 29
N_both (for agreement): 29
Percent agreement: 1.000
Cohen's kappa: nan
------------------------------------------------------------
=== Question: seed_reproducibility ===
TS label counts:
seed_reproducibility_TS
No     19
Yes    10
Name: count, dtype: int64

RG label counts:
seed_reproducibility_RG
No     20
Yes     9
Name: count, dtype: int64

N_TS (non-null): 29
N_RG (non-null): 29
N_both (for agreement): 29
Percent agreement: 0.690
Cohen's kappa: 0.296
------------------------------------------------------------
=== Question: hardware_requirements ===
TS label counts:
hardware_requirements_TS
No     28
Yes     1
Name: count, dtype: int64

RG label counts:
hardware_requirements_RG
No     28
Yes     1
Name: count, dtype: int64

N_TS (non-null): 29
N_RG (non-null): 29
N_both (for agreement): 29
Percent agreement: 1.000
Cohen's kappa: 1.000
------------------------------------------------------------
=== Question: reporting_guidance ===
TS label counts:
reporting_guidance_TS
No     28
Yes     1
Name: count, dtype: int64

RG label counts:
reporting_guidance_RG
No    29
Name: count, dtype: int64

N_TS (non-null): 29
N_RG (non-null): 29
N_both (for agreement): 29
Percent agreement: 0.966
Cohen's kappa: 0.000
------------------------------------------------------------
=== Question: link_to_paper ===
TS label counts:
link_to_paper_TS
No     24
Yes     5
Name: count, dtype: int64

RG label counts:
link_to_paper_RG
No     23
Yes     6
Name: count, dtype: int64

N_TS (non-null): 29
N_RG (non-null): 29
N_both (for agreement): 29
Percent agreement: 0.966
Cohen's kappa: 0.888
------------------------------------------------------------
=== Question: citation_file ===
TS label counts:
citation_file_TS
No     22
Yes     7
Name: count, dtype: int64

RG label counts:
citation_file_RG
No     21
Yes     8
Name: count, dtype: int64

N_TS (non-null): 29
N_RG (non-null): 29
N_both (for agreement): 29
Percent agreement: 0.966
Cohen's kappa: 0.910
------------------------------------------------------------
=== Question: api_version_documented ===
TS label counts:
api_version_documented_TS
Not Applicable    28
No                 1
Name: count, dtype: int64

RG label counts:
api_version_documented_RG
Not Applicable    29
Name: count, dtype: int64

N_TS (non-null): 29
N_RG (non-null): 29
N_both (for agreement): 29
Percent agreement: 0.966
Cohen's kappa: 0.000
------------------------------------------------------------
=== Question: sample_dataset ===
TS label counts:
sample_dataset_TS
No     23
Yes     6
Name: count, dtype: int64

RG label counts:
sample_dataset_RG
No     24
Yes     5
Name: count, dtype: int64

N_TS (non-null): 29
N_RG (non-null): 29
N_both (for agreement): 29
Percent agreement: 0.966
Cohen's kappa: 0.888
------------------------------------------------------------
=== Question: dataset_link ===
TS label counts:
dataset_link_TS
Not Applicable    19
No                 8
Yes                2
Name: count, dtype: int64

RG label counts:
dataset_link_RG
Not Applicable    24
No                 5
Name: count, dtype: int64

N_TS (non-null): 29
N_RG (non-null): 29
N_both (for agreement): 29
Percent agreement: 0.621
Cohen's kappa: 0.075
------------------------------------------------------------
=== Question: confidential_data_excluded ===
TS label counts:
confidential_data_excluded_TS
Yes    27
No      2
Name: count, dtype: int64

RG label counts:
confidential_data_excluded_RG
No    29
Name: count, dtype: int64

N_TS (non-null): 29
N_RG (non-null): 29
N_both (for agreement): 29
Percent agreement: 0.069
Cohen's kappa: 0.000
------------------------------------------------------------
=== Question: env_variables_used ===
TS label counts:
env_variables_used_TS
No     25
Yes     4
Name: count, dtype: int64

RG label counts:
env_variables_used_RG
No     26
Yes     3
Name: count, dtype: int64

N_TS (non-null): 29
N_RG (non-null): 29
N_both (for agreement): 29
Percent agreement: 0.759
Cohen's kappa: -0.134
------------------------------------------------------------

=== Summary table (per-question agreement) ===
                      question  N_TS  N_RG  N_both  agreement     kappa
17      api_version_documented    29    29      29   0.965517  0.000000
11                ci_framework    29    29      29   1.000000       NaN
16               citation_file    29    29      29   0.965517  0.910217
6           coding_conventions    29    29      29   0.586207  0.292683
20  confidential_data_excluded    29    29      29   0.068966  0.000000
19                dataset_link    29    29      29   0.620690  0.075362
4          dependency_versions    29    29      29   0.965517  0.888031
21          env_variables_used    29    29      29   0.758621 -0.134078
13       hardware_requirements    29    29      29   1.000000  1.000000
8         inline_documentation    29    29      29   0.689655  0.382979
5             license_included    29    29      29   1.000000  1.000000
15               link_to_paper    29    29      29   0.965517  0.888031
7             linter_formatter    29    29      29   1.000000       NaN
9                   modularity    29    29      29   0.931034  0.848168
1              readme_included    29    29      29   1.000000  1.000000
2              readme_overview    29    29      29   0.724138  0.442308
0                   repo_empty    29    29      29   0.965517  0.000000
14          reporting_guidance    29    29      29   0.965517  0.000000
3        requirements_included    29    29      29   0.862069  0.632911
18              sample_dataset    29    29      29   0.965517  0.888031
12        seed_reproducibility    29    29      29   0.689655  0.296496
10                unit_testing    29    29      29   0.965517  0.000000

/opt/homebrew/Caskroom/miniforge/base/envs/Thomas/lib/python3.13/site-packages/sklearn/metrics/_classification.py:534: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/Thomas/lib/python3.13/site-packages/sklearn/metrics/_classification.py:897: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)
/opt/homebrew/Caskroom/miniforge/base/envs/Thomas/lib/python3.13/site-packages/sklearn/metrics/_classification.py:534: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/Thomas/lib/python3.13/site-packages/sklearn/metrics/_classification.py:897: RuntimeWarning: invalid value encountered in scalar divide
  k = np.sum(w_mat * confusion) / np.sum(w_mat * expected)

In [6]:
import pandas as pd

# Disable wrapping for long URLs
pd.set_option("display.max_colwidth", None)

# Sets of annotated PMCIDs
pmcids_TS = set(df_TS["PMCID"])
pmcids_RG = set(df_RG["PMCID"])

# Differences
only_TS = pmcids_TS - pmcids_RG
only_RG = pmcids_RG - pmcids_TS

print("=== Annotated by TS but NOT by RG ===")
print(
    df_TS[df_TS["PMCID"].isin(only_TS)][["PMCID", "repo_url"]]
       .sort_values("PMCID")
)

print("\n=== Annotated by RG but NOT by TS ===")
print(
    df_RG[df_RG["PMCID"].isin(only_RG)][["PMCID", "repo_url"]]
       .sort_values("PMCID")
)

=== Annotated by TS but NOT by RG ===
         PMCID                         repo_url
11  PMC9685866  https://doi.org/10.57770/QTYQZS

=== Annotated by RG but NOT by TS ===
          PMCID  \
19  PMC10844815
0   PMC11307559
17  PMC11992218
28   PMC8784888

                                                                                     repo_url
19                                             https://github.com/yiwangz/SS_learning/MLinHCT
0                                      https://seakheeoh76.shinyapps.io/XGBoost_BA_prediction
17                                                  https://www.cdc.gov/nchs/nhanes/index.htm
28  https://github.com/AkihiroShiroshita/Prediction-model-for-Pnuemonic-COPD-exacerbation.git

In [8]:
def compare_annotation_column(colname, df_TS=df_TS, df_RG=df_RG):
    """
    Display rows where TS and RG disagree for a given annotation column.
    colname should be one of the annotation fields, e.g., 'repo_empty'.
    """
    # PMCIDs annotated by both
    pmcids_both = set(df_TS["PMCID"]) & set(df_RG["PMCID"])

    # Filter to overlapping annotations
    TS_both = df_TS[df_TS["PMCID"].isin(pmcids_both)]
    RG_both = df_RG[df_RG["PMCID"].isin(pmcids_both)]

    # Merge side-by-side
    df_compare = TS_both[["PMCID", "repo_url", colname]].merge(
        RG_both[["PMCID", "repo_url", colname]],
        on=["PMCID", "repo_url"],
        suffixes=("_TS", "_RG")
    )

    # Keep only disagreements
    df_disagree = df_compare[
        df_compare[f"{colname}_TS"] != df_compare[f"{colname}_RG"]
    ].sort_values("PMCID")

    return df_disagree

In [1]:
question_cols = [
    "repo_empty",
    "readme_included",
    "readme_overview",
    "requirements_included",
    "dependency_versions",
    "license_included",
    "coding_conventions",
    "linter_formatter",
    "inline_documentation",
    "modularity",
    "unit_testing",
    "ci_framework",
    "seed_reproducibility",
    "hardware_requirements",
    "reporting_guidance",
    "link_to_paper",
    "citation_file",
    "api_version_documented",
    "sample_dataset",
    "dataset_link",
    "confidential_data_excluded",
    "env_variables_used",
]

In [15]:
question_cols = [
    "repo_empty",
    "readme_included",
    "readme_overview",
    "requirements_included",
    "dependency_versions",
    "license_included",
    "coding_conventions",
    "linter_formatter",
    "inline_documentation",
    "modularity",
    "unit_testing",
    "ci_framework",
    "seed_reproducibility",
    "hardware_requirements",
    "reporting_guidance",
    "link_to_paper",
    "citation_file",
    "api_version_documented",
    "sample_dataset",
    "dataset_link",
    "confidential_data_excluded",
    "env_variables_used",
]

def compare_annotation_column(colname, df_TS, df_RG):
    pmcids_both = set(df_TS["PMCID"]) & set(df_RG["PMCID"])
    TS_both = df_TS[df_TS["PMCID"].isin(pmcids_both)]
    RG_both = df_RG[df_RG["PMCID"].isin(pmcids_both)]

    df_compare = TS_both[["PMCID", "repo_url", colname]].merge(
        RG_both[["PMCID", "repo_url", colname]],
        on=["PMCID", "repo_url"],
        suffixes=("_TS", "_RG")
    )

    df_disagree = df_compare[
        df_compare[f"{colname}_TS"] != df_compare[f"{colname}_RG"]
    ].sort_values("PMCID")

    return df_disagree


# Loop and display disagreements for each question
for col in question_cols:
    print(f"=== Disagreements for: {col} ===")
    df_dis = compare_annotation_column(col, df_TS, df_RG)

    if df_dis.empty:
        print("No disagreements.\n")
    else:
        display(df_dis)
        print("\n")

=== Disagreements for: repo_empty ===

         PMCID                            repo_url repo_empty_TS repo_empty_RG
1  PMC11701130  https://github.com/CalvinSMU/AiLES           Yes            No

=== Disagreements for: readme_included ===
No disagreements.

=== Disagreements for: readme_overview ===

,PMCID,repo_url,readme_overview_TS,readme_overview_RG
26,PMC10100433,https://github.com/damiankotevski/head-and-neck-cancer-specific-survival,Yes,No
16,PMC10844206,https://github.com/benli12345/LEO-ML-NSQIP,No,Yes
24,PMC11722487,https://github.com/weissman-lab/restriction,No,Yes
0,PMC12121029,https://github.com/EnzhaoZhu/Common-risks-prediction-among-psychiatric-inpatients,No,Yes
27,PMC8290951,https://github.com/mottenhoff/covid19_CDSS,Yes,No
8,PMC8881932,https://doi.org/10.5281/zenodo.4560078,No,Yes
15,PMC9872743,https://github.com/JohnLeo-XJTU/PerLesionDet_for_Oph-The,Yes,No
21,PMC9913376,https://github.com/LFairleySmith/MyelomaPrediction,Yes,No

=== Disagreements for: requirements_included ===

,PMCID,repo_url,requirements_included_TS,requirements_included_RG
3,PMC11040883,https://github.com/laamit/champCalculator,Yes,No
24,PMC11722487,https://github.com/weissman-lab/restriction,Yes,No
17,PMC7797735,https://github.com/carsaesi/covid19sdtool,Yes,No
6,PMC9720950,https://github.com/mi-erasmusmc/EmcDementiaModelValidation,Yes,No

=== Disagreements for: dependency_versions ===

,PMCID,repo_url,dependency_versions_TS,dependency_versions_RG
3,PMC11040883,https://github.com/laamit/champCalculator,Yes,No

=== Disagreements for: license_included ===
No disagreements.

=== Disagreements for: coding_conventions ===

,PMCID,repo_url,coding_conventions_TS,coding_conventions_RG
19,PMC10491759,https://github.com/ShinyShine-820/LPAprediction,Yes,No
18,PMC10937994,https://github.com/bounassif/Adenoma-Detector,Yes,No
3,PMC11040883,https://github.com/laamit/champCalculator,Yes,No
22,PMC11257923,https://github.com/tsryo/evalFL,Yes,No
0,PMC12121029,https://github.com/EnzhaoZhu/Common-risks-prediction-among-psychiatric-inpatients,Yes,No
11,PMC6461273,https://osf.io/w7aes/,Yes,No
17,PMC7797735,https://github.com/carsaesi/covid19sdtool,Yes,No
2,PMC8932490,https://github.com/Aneja-Lab-Yale/Aneja-Lab-Public-Adversarial-Imaging,Yes,No
7,PMC9653436,https://github.com/Dexin-Chen/Pathomics-analysis,Yes,No
6,PMC9720950,https://github.com/mi-erasmusmc/EmcDementiaModelValidation,Yes,No
15,PMC9872743,https://github.com/JohnLeo-XJTU/PerLesionDet_for_Oph-The,Yes,No
13,PMC9978473,https://github.com/putzfn/HNLNL_autosegmentation_trained_models,Yes,No

=== Disagreements for: linter_formatter ===
No disagreements.

=== Disagreements for: inline_documentation ===

,PMCID,repo_url,inline_documentation_TS,inline_documentation_RG
26,PMC10100433,https://github.com/damiankotevski/head-and-neck-cancer-specific-survival,No,Yes
3,PMC11040883,https://github.com/laamit/champCalculator,No,Yes
0,PMC12121029,https://github.com/EnzhaoZhu/Common-risks-prediction-among-psychiatric-inpatients,Yes,No
10,PMC6413892,https://github.com/dt433/Predict-Prostate,Yes,No
11,PMC6461273,https://osf.io/w7aes/,Yes,No
8,PMC8881932,https://doi.org/10.5281/zenodo.4560078,No,Yes
6,PMC9720950,https://github.com/mi-erasmusmc/EmcDementiaModelValidation,Yes,No
15,PMC9872743,https://github.com/JohnLeo-XJTU/PerLesionDet_for_Oph-The,Yes,No
9,PMC9898833,https://github.com/jacksoncoki/Emergency-data-processing,Yes,No

=== Disagreements for: modularity ===

,PMCID,repo_url,modularity_TS,modularity_RG
24,PMC11722487,https://github.com/weissman-lab/restriction,Yes,No
6,PMC9720950,https://github.com/mi-erasmusmc/EmcDementiaModelValidation,Yes,No

=== Disagreements for: unit_testing ===

,PMCID,repo_url,unit_testing_TS,unit_testing_RG
3,PMC11040883,https://github.com/laamit/champCalculator,Yes,No

=== Disagreements for: ci_framework ===
No disagreements.

=== Disagreements for: seed_reproducibility ===

,PMCID,repo_url,seed_reproducibility_TS,seed_reproducibility_RG
20,PMC10077108,https://github.com/mgregorich/BEAt-DKD_PredeGFR,No,Yes
26,PMC10100433,https://github.com/damiankotevski/head-and-neck-cancer-specific-survival,No,Yes
19,PMC10491759,https://github.com/ShinyShine-820/LPAprediction,No,Yes
5,PMC10658003,https://github.com/IreneSophia/MLSPE,No,Yes
25,PMC10955037,https://github.com/Exeter-Diabetes/CPRD-Pedro-SGLT2vsGLP1,Yes,No
24,PMC11722487,https://github.com/weissman-lab/restriction,Yes,No
11,PMC6461273,https://osf.io/w7aes/,Yes,No
8,PMC8881932,https://doi.org/10.5281/zenodo.4560078,Yes,No
7,PMC9653436,https://github.com/Dexin-Chen/Pathomics-analysis,Yes,No

=== Disagreements for: hardware_requirements ===
No disagreements.

=== Disagreements for: reporting_guidance ===

,PMCID,repo_url,reporting_guidance_TS,reporting_guidance_RG
15,PMC9872743,https://github.com/JohnLeo-XJTU/PerLesionDet_for_Oph-The,Yes,No

=== Disagreements for: link_to_paper ===

,PMCID,repo_url,link_to_paper_TS,link_to_paper_RG
28,PMC11827575,https://github.com/MGensheimer/prognosis-model,No,Yes

=== Disagreements for: citation_file ===

,PMCID,repo_url,citation_file_TS,citation_file_RG
24,PMC11722487,https://github.com/weissman-lab/restriction,No,Yes

=== Disagreements for: api_version_documented ===

,PMCID,repo_url,api_version_documented_TS,api_version_documented_RG
27,PMC8290951,https://github.com/mottenhoff/covid19_CDSS,No,Not Applicable

=== Disagreements for: sample_dataset ===

,PMCID,repo_url,sample_dataset_TS,sample_dataset_RG
15,PMC9872743,https://github.com/JohnLeo-XJTU/PerLesionDet_for_Oph-The,Yes,No

=== Disagreements for: dataset_link ===

,PMCID,repo_url,dataset_link_TS,dataset_link_RG
4,PMC10545794,https://github.com/TheDecodeLab/Prediction_of_CDI_by_EHR_and_Genetics,No,Not Applicable
5,PMC10658003,https://github.com/IreneSophia/MLSPE,No,Not Applicable
16,PMC10844206,https://github.com/benli12345/LEO-ML-NSQIP,No,Not Applicable
12,PMC11624760,https://github.com/sersanmarsergio/SGA_prediction,No,Not Applicable
24,PMC11722487,https://github.com/weissman-lab/restriction,Not Applicable,No
27,PMC8290951,https://github.com/mottenhoff/covid19_CDSS,Yes,Not Applicable
14,PMC8593277,https://github.com/KosorokLab/CovidIBDRiskCalc,Yes,Not Applicable
8,PMC8881932,https://doi.org/10.5281/zenodo.4560078,Not Applicable,No
7,PMC9653436,https://github.com/Dexin-Chen/Pathomics-analysis,No,Not Applicable
6,PMC9720950,https://github.com/mi-erasmusmc/EmcDementiaModelValidation,No,Not Applicable
9,PMC9898833,https://github.com/jacksoncoki/Emergency-data-processing,Not Applicable,No

=== Disagreements for: confidential_data_excluded ===

,PMCID,repo_url,confidential_data_excluded_TS,confidential_data_excluded_RG
20,PMC10077108,https://github.com/mgregorich/BEAt-DKD_PredeGFR,Yes,No
26,PMC10100433,https://github.com/damiankotevski/head-and-neck-cancer-specific-survival,Yes,No
19,PMC10491759,https://github.com/ShinyShine-820/LPAprediction,Yes,No
4,PMC10545794,https://github.com/TheDecodeLab/Prediction_of_CDI_by_EHR_and_Genetics,Yes,No
5,PMC10658003,https://github.com/IreneSophia/MLSPE,Yes,No
16,PMC10844206,https://github.com/benli12345/LEO-ML-NSQIP,Yes,No
18,PMC10937994,https://github.com/bounassif/Adenoma-Detector,Yes,No
25,PMC10955037,https://github.com/Exeter-Diabetes/CPRD-Pedro-SGLT2vsGLP1,Yes,No
22,PMC11257923,https://github.com/tsryo/evalFL,Yes,No
12,PMC11624760,https://github.com/sersanmarsergio/SGA_prediction,Yes,No
24,PMC11722487,https://github.com/weissman-lab/restriction,Yes,No
28,PMC11827575,https://github.com/MGensheimer/prognosis-model,Yes,No
23,PMC11938237,https://github.com/SCYAN0401/Predict-GC-LNM,Yes,No
0,PMC12121029,https://github.com/EnzhaoZhu/Common-risks-prediction-among-psychiatric-inpatients,Yes,No
10,PMC6413892,https://github.com/dt433/Predict-Prostate,Yes,No
11,PMC6461273,https://osf.io/w7aes/,Yes,No
17,PMC7797735,https://github.com/carsaesi/covid19sdtool,Yes,No
27,PMC8290951,https://github.com/mottenhoff/covid19_CDSS,Yes,No
14,PMC8593277,https://github.com/KosorokLab/CovidIBDRiskCalc,Yes,No
8,PMC8881932,https://doi.org/10.5281/zenodo.4560078,Yes,No
2,PMC8932490,https://github.com/Aneja-Lab-Yale/Aneja-Lab-Public-Adversarial-Imaging,Yes,No
7,PMC9653436,https://github.com/Dexin-Chen/Pathomics-analysis,Yes,No
6,PMC9720950,https://github.com/mi-erasmusmc/EmcDementiaModelValidation,Yes,No
15,PMC9872743,https://github.com/JohnLeo-XJTU/PerLesionDet_for_Oph-The,Yes,No
9,PMC9898833,https://github.com/jacksoncoki/Emergency-data-processing,Yes,No
21,PMC9913376,https://github.com/LFairleySmith/MyelomaPrediction,Yes,No
13,PMC9978473,https://github.com/putzfn/HNLNL_autosegmentation_trained_models,Yes,No

=== Disagreements for: env_variables_used ===

,PMCID,repo_url,env_variables_used_TS,env_variables_used_RG
26,PMC10100433,https://github.com/damiankotevski/head-and-neck-cancer-specific-survival,No,Yes
28,PMC11827575,https://github.com/MGensheimer/prognosis-model,No,Yes
0,PMC12121029,https://github.com/EnzhaoZhu/Common-risks-prediction-among-psychiatric-inpatients,Yes,No
27,PMC8290951,https://github.com/mottenhoff/covid19_CDSS,Yes,No
2,PMC8932490,https://github.com/Aneja-Lab-Yale/Aneja-Lab-Public-Adversarial-Imaging,Yes,No
6,PMC9720950,https://github.com/mi-erasmusmc/EmcDementiaModelValidation,Yes,No
15,PMC9872743,https://github.com/JohnLeo-XJTU/PerLesionDet_for_Oph-The,No,Yes

In [11]:
compare_annotation_column("repo_empty")

         PMCID                            repo_url repo_empty_TS repo_empty_RG
1  PMC11701130  https://github.com/CalvinSMU/AiLES           Yes            No

In [12]:
compare_annotation_column("readme_included")

Empty DataFrame
Columns: [PMCID, repo_url, readme_included_TS, readme_included_RG]
Index: []

In [13]:
compare_annotation_column("readme_overview")

,PMCID,repo_url,readme_overview_TS,readme_overview_RG
26,PMC10100433,https://github.com/damiankotevski/head-and-neck-cancer-specific-survival,Yes,No
16,PMC10844206,https://github.com/benli12345/LEO-ML-NSQIP,No,Yes
24,PMC11722487,https://github.com/weissman-lab/restriction,No,Yes
0,PMC12121029,https://github.com/EnzhaoZhu/Common-risks-prediction-among-psychiatric-inpatients,No,Yes
27,PMC8290951,https://github.com/mottenhoff/covid19_CDSS,Yes,No
8,PMC8881932,https://doi.org/10.5281/zenodo.4560078,No,Yes
15,PMC9872743,https://github.com/JohnLeo-XJTU/PerLesionDet_for_Oph-The,Yes,No
21,PMC9913376,https://github.com/LFairleySmith/MyelomaPrediction,Yes,No

In [14]:
compare_annotation_column("requirements_included")

,PMCID,repo_url,requirements_included_TS,requirements_included_RG
3,PMC11040883,https://github.com/laamit/champCalculator,Yes,No
24,PMC11722487,https://github.com/weissman-lab/restriction,Yes,No
17,PMC7797735,https://github.com/carsaesi/covid19sdtool,Yes,No
6,PMC9720950,https://github.com/mi-erasmusmc/EmcDementiaModelValidation,Yes,No

In [ ]:
compare_annotation_column("dependency_versions"